### ISSUE TITLE
CLARIN helpdesk link should have responsible/ownerIDs

### ISSUE THREAD

**Issue by flammie** [clarin-eric/fcs-sru-aggregator#3]
Here:
https://github.com/clarin-eric/fcs-sru-aggregator/blob/master/src/main/resources/assets/js/pages/helppage.jsx#L11

There's some documentation in https://github.com/hzsk/clarind-helpdesk,

**Comment by dietervu** [comment]
Thanks for the input! I would rather use an email address (like fcs@clarin.eu) for the support than a webform, because:

- this does not require the code to be changed and updated frequently
- it is more efficient for the end user: no captcha required, no need to enter your name and email separately, possibility to include screenshots etc

Of course the email address could still be connected to the helpdesk. This also holds for the LR Swtichboard support, see:

https://github.com/clarin-eric/LRSwitchboard/issues/56

**Comment by flammie** [comment]
Replacing the helpdesk button with an email link sounds ok for me, just wanted to note that the current setup will seemingly just at very least not reach the right people very soon as the tickets will land in sorting queue and there's possibly no users in the ticketing system for FCS help.
